# Generated by Django 5.2.13 on 2026-05-02 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_rename_books_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author_photo',
            new_name='photo_author',
        ),
    ]
