# Generated by Django 5.2.13 on 2026-05-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0005_alter_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_rental_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
